name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      # Setup rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      # Check formatting
      - run: cargo fmt --all -- --check
      # Check code with clippy
      - run: cargo clippy --all --all-targets -- -D warnings
      # # Setup Node and Bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11
      # Install dependencies
      - run: bun install
      # Check that the code is formatted correctly
      - run: bun prettier --check .
      # Check that the code is linted correctly
      - run: bun eslint --max-warnings 0 .
      # Check toml
      - run: bun taplo check
      # Build
      - run: bun run build
      # Run tests
      - run: bun run test
